CREATE DATABASE IF NOT EXISTS Fluvip;

USE Fluvip;

CREATE TABLE IF NOT EXISTS Person (
    ID INT NOT NULL AUTO_INCREMENT,
    Names VARCHAR(255) NOT NULL,
    Surnames VARCHAR(255),
    Document VARCHAR(255) NOT NULL,
    Telephone VARCHAR(255),
    PRIMARY KEY (ID)
);